<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\erpWeb.Core\erpWeb.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="MailKit" />
    <PackageReference Include="ClosedXML" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="erpWeb.UnitTests" />
  </ItemGroup>

</Project>
