<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <!-- Seul package d'accès aux données autorisé dans Core (DbSet<T>, LINQ asynchrone) -->
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" />
    <PackageReference Include="Mapster" />
    <PackageReference Include="Mapster.DependencyInjection" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>

</Project>
