<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>erpWeb-7c1f3e2a-socle</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\erpWeb.Core\erpWeb.Core.csproj" />
    <ProjectReference Include="..\erpWeb.Infrastructure\erpWeb.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Web.LibraryManager.Build" />
  </ItemGroup>

</Project>
